Anfaengerpraktikum: Player Class Reference
Player Class Reference
Klasse für den Spielercharakter. Verwaltet Bewegung, Sprünge, Angriffe und Animationen.
Public Member Functions
override void _Ready ()
Initialisierung der Referenzen. Findet die relevanten Knoten in der Szene und weist sie zu.
override void _PhysicsProcess (double DeltaTime)
Physikalische Prozesse werden in jedem Frame ausgeführt. Berechnet Gravitation, Bewegung, Sprünge und Dashes.
bool IsAttacking ()
Überprüft, ob der Spieler gerade angreift.
bool IsBlocking ()
Überprüft, ob der Spieler blockiert.
void MaxHeal ()
Heilt den Spieler vollständig, indem die aktuellen Lebenspunkte auf das Maximum gesetzt werden.
void TakeDamage (Damage Damage)
Wendet Schaden auf den Spieler an. Reduziert die aktuellen Lebenspunkte basierend auf dem übergebenen Schaden und wendet einen Rückstoßeffekt an.
Damage GetDamage ()
Gibt den Schaden zurück, den der Spieler mit seinem aktuellen Angriff verursacht. Der Schaden basiert auf der letzten Angriffsmethode (light_attack oder heavy_attack).
void RegenerateStamina (float Amount, double delta)
Regeneriert die Stamina des Spielers, wenn er für eine bestimmte Zeit keine Stamina-verbrauchende Aktion durchgeführt hat.
bool UseStamina (float Amount)
Verbraucht eine bestimmte Menge an Stamina, falls genügend verfügbar ist. Setzt den Inaktivitäts-Timer zurück, wenn Stamina verbraucht wird.
void SlowPlayer (float SlowAmount)
Verlangsamt den Spieler um einen bestimmten Prozentsatz.
void Respawn ()
Lässt den Spieler am Checkpoint spawnen.
BloodVial GetBloodVials ()
Getter für BloodVials.
void SetSinAmount (int Value)
Setzt den SinAmount des Spielers.
Private Member Functions
void HandleJump ()
Verarbeitet die Sprunglogik. Setzt den Sprungzähler zurück und ermöglicht einen Doppelsprung.
void HandleMovement (double DeltaTime)
Verarbeitet die Bewegung des Spielers. Regelt normale Bewegungen, Dashes und Kollisionen.
void StartDash ()
Startet den Dash-Prozess.
void DashInProgress (double DeltaTime)
Führt die Logik während eines Dashes aus.
void CreateDashEffect ()
Erstellt einen visuellen Dash-Trail. Der Spieler hinterlässt eine Spur während des Dashes.
void StopDash ()
Stoppt den Dash.
void OnSpawn (Vector2 position, string direction)
Wird aufgerufen, wenn der Spieler an einer neuen Position spawnen soll.
void UpdateAnimations ()
Aktualisiert die Animationen des Spielers.
Private Attributes
int JumpMax = 2
int JumpCount = 0
Vector2 DashDirection = Vector2.Zero
float DashSpeed = 300f
bool IsDashing = false
bool CanDash = true
float DashTrailInterval = 0.05f
float DashTrailTimer = 0f
AnimationPlayer AnimationPlayer
Sprite2D Sprite
Timer DashEffect
Timer DashTimer
CollisionShape2D SwordCollision
CollisionShape2D PlayerHitbox
BloodVial BloodVials
Label SinDisplay
Vector2 HauptHitbox
int LastAttack = 0
float TimeSinceLastStaminaUse = 0f
Static Private Attributes
const float SPEED = 100f
const float JUMP_VELOCITY = -300f
Detailed Description
Klasse für den Spielercharakter. Verwaltet Bewegung, Sprünge, Angriffe und Animationen.
Definition at line 8 of file Player.cs.
Member Function Documentation
_PhysicsProcess()
override void Player._PhysicsProcess (double DeltaTime) inline
Physikalische Prozesse werden in jedem Frame ausgeführt. Berechnet Gravitation, Bewegung, Sprünge und Dashes.
Parameters
DeltaTime Zeit seit dem letzten Frame.
Definition at line 67 of file Player.cs.
{
        // Gravitation hinzufügen, wenn der Charakter nicht am Boden ist
        if (!IsOnFloor()) {
            Velocity += GetGravity() * (float)DeltaTime;
        } else {
            CanDash = true; // Dash wird zurückgesetzt, wenn der Charakter am Boden ist
        }
        TimeSinceLastStaminaUse += (float)DeltaTime;
        RegenerateStamina(20f, DeltaTime);
        // Heal
        if(Input.IsActionJustPressed("heal")){
            BloodVials.UseBloodVial();
        }
        HandleJump();
        HandleMovement(DeltaTime);
        MoveAndSlide();
        UpdateAnimations();
        PlayerStats.Instance.SetPosition(Position);
        }
References BloodVials, CanDash, HandleJump(), HandleMovement(), PlayerStats.Instance, RegenerateStamina(), PlayerStats.SetPosition(), TimeSinceLastStaminaUse, UpdateAnimations(), and BloodVial.UseBloodVial().
_Ready()
override void Player._Ready () inline
Initialisierung der Referenzen. Findet die relevanten Knoten in der Szene und weist sie zu.
Definition at line 43 of file Player.cs.
{
        AnimationPlayer = GetNode<AnimationPlayer>("AnimationPlayer");
        Sprite = GetNode<Sprite2D>("Sprite2D");
        DashEffect = GetNode<Timer>("DashEffect");
        DashTimer = GetNode<Timer>("DashTimer");
        SwordCollision = GetNode<CollisionShape2D>("Sprite2D/SwordHit/SwordCollision");
        PlayerHitbox = GetNode<CollisionShape2D>("PlayerHitbox");
        HauptHitbox = PlayerHitbox.Position;
        BloodVials = GetNode<BloodVial>("../HUD/BloodVial/Counter");
        SinDisplay = GetNode<Label>("../HUD/SinAmount/Counter");
        SinDisplay.Text = PlayerStats.Instance.GetSinAmount() + "";
        NavigationManager navigationManager = GetNode<NavigationManager>("/root/NavigationManager");
        navigationManager.Connect("OnTriggerPlayerSpawn", new Callable(this, nameof(OnSpawn)));
        Position = PlayerStats.Instance.GetPosition();
    }
References AnimationPlayer, BloodVials, DashEffect, DashTimer, PlayerStats.GetPosition(), PlayerStats.GetSinAmount(), HauptHitbox, PlayerStats.Instance, OnSpawn(), PlayerHitbox, SinDisplay, Sprite, and SwordCollision.
CreateDashEffect()
void Player.CreateDashEffect () inline private
Erstellt einen visuellen Dash-Trail. Der Spieler hinterlässt eine Spur während des Dashes.
Definition at line 207 of file Player.cs.
{
        Sprite2D PlayerCopyNode = (Sprite2D)Sprite.Duplicate();
        GetParent().AddChild(PlayerCopyNode);
        CollisionShape2D SwordCollisionCopy = PlayerCopyNode.GetNode<CollisionShape2D>("SwordHit/SwordCollision");
        if (SwordCollisionCopy != null) {
            SwordCollisionCopy.Disabled = true; // Deaktiviere die Kollision der Kopie
        }
        PlayerCopyNode.GlobalPosition = GlobalPosition + new Vector2(0, Sprite.Texture.GetHeight() * Sprite.Scale.Y * -0.5f);
        // Verblassen-Effekt für den Dash-Trail hinzufügen
        float AnimationTime = (float)(DashTimer.WaitTime / 3);
        Timer FadeTimer1 = new Timer();
        AddChild(FadeTimer1);
        FadeTimer1.Timeout += () => {
            if (IsInstanceValid(PlayerCopyNode)) {
                PlayerCopyNode.Modulate = new Color(PlayerCopyNode.Modulate, 0.4f);
            }
        };
        FadeTimer1.Start(AnimationTime);
        Timer FadeTimer2 = new Timer();
        AddChild(FadeTimer2);
        FadeTimer2.Timeout += () => {
            if (IsInstanceValid(PlayerCopyNode)) {
                PlayerCopyNode.Modulate = new Color(PlayerCopyNode.Modulate, 0.2f);
            }
        };
        FadeTimer2.Start(AnimationTime * 2);
        Timer FadeTimer3 = new Timer();
        AddChild(FadeTimer3);
        FadeTimer3.Timeout += () => {
            if (IsInstanceValid(PlayerCopyNode)) {
                PlayerCopyNode.QueueFree();
            }
        };
        FadeTimer3.Start(AnimationTime * 3);
    }
References DashTimer, and Sprite.
Referenced by DashInProgress().
DashInProgress()
void Player.DashInProgress (double DeltaTime) inline private
Führt die Logik während eines Dashes aus.
Parameters
DeltaTime Zeit seit dem letzten Frame.
Definition at line 187 of file Player.cs.
{
        // Charakter bewegt sich in die Dash-Richtung mit Dash-Geschwindigkeit
        if (DashDirection == Vector2.Up) {
            Velocity = DashDirection / 1.5f * DashSpeed;
        } else {
            Velocity = DashDirection * DashSpeed;
        }
        // Dash-Trail bei Intervallen erstellen
        DashTrailTimer -= (float)DeltaTime;
        if (DashTrailTimer <= 0f) {
            CreateDashEffect();
            DashTrailTimer = DashTrailInterval;
        }
    }
References CreateDashEffect(), DashDirection, DashSpeed, DashTrailInterval, and DashTrailTimer.
Referenced by HandleMovement().
GetBloodVials()
BloodVial Player.GetBloodVials () inline
Getter für BloodVials.
Returns
BloodVial
Definition at line 383 of file Player.cs.
{
        return BloodVials;
    }
References BloodVials.
Referenced by Checkpoint.OnPlayerBodyEntered().
GetDamage()
Damage Player.GetDamage () inline
Gibt den Schaden zurück, den der Spieler mit seinem aktuellen Angriff verursacht. Der Schaden basiert auf der letzten Angriffsmethode (light_attack oder heavy_attack).
Returns
Eine Instanz der Klasse Damage, die den physischen Schaden, wahren Schaden und Rückstoß enthält.
Definition at line 317 of file Player.cs.
{
        if(LastAttack == 1){
            return new Damage(50, 0, Vector2.Zero, this);
        }
        if(LastAttack == 2){
            Vector2 Push = new Vector2(20,0);
            if(Sprite.FlipH){
                Push = -Push;
            }
            return new Damage(100, 0, Push, this);
        }
        return new Damage(0,0,Vector2.Zero, this);
    }
References LastAttack, and Sprite.
Referenced by BaseEnemy.OnHitboxAreaEntered().
HandleJump()
void Player.HandleJump () inline private
Verarbeitet die Sprunglogik. Setzt den Sprungzähler zurück und ermöglicht einen Doppelsprung.
Definition at line 94 of file Player.cs.
{
        // Sprungzähler zurücksetzen, wenn der Charakter am Boden ist
        if (JumpCount != 0 && IsOnFloor()) {
            JumpCount = 0;
        }
        // Überprüfen, ob der Sprung-Button gedrückt wurde und der Charakter noch Sprünge übrig hat
        if (Input.IsActionJustPressed("ui_up") && JumpCount < JumpMax) {
            if (JumpCount == 0) {
            // Erster Sprung ohne Stamina-Verlust
            Velocity = new Vector2(Velocity.X, JUMP_VELOCITY);
            JumpCount += 1;
            } else if (JumpCount > 0) {
                // Beim Doppelsprung Stamina prüfen und abziehen
                if (UseStamina(15)) {
                    Velocity = new Vector2(Velocity.X, JUMP_VELOCITY);
                    JumpCount += 1;
                }
            }
        }
    }
References JUMP_VELOCITY, JumpCount, JumpMax, and UseStamina().
Referenced by _PhysicsProcess().
HandleMovement()
void Player.HandleMovement (double DeltaTime) inline private
Verarbeitet die Bewegung des Spielers. Regelt normale Bewegungen, Dashes und Kollisionen.
Parameters
DeltaTime Zeit seit dem letzten Frame.
Definition at line 121 of file Player.cs.
{
        Vector2 direction = new Vector2(Input.GetAxis("ui_left", "ui_right"), Input.GetAxis("ui_up", "ui_down")).Normalized();
        float currentSpeed = SPEED;
        // Sprite umdrehen basierend auf der Bewegungsrichtung und Kollision umdrehen
        if (direction.X < 0) {
            Sprite.FlipH = true;
            SwordCollision.Position = new Vector2(-Mathf.Abs(SwordCollision.Position.X), SwordCollision.Position.Y);
            PlayerHitbox.Position = new Vector2(Sprite.Position.X * 1.8f, PlayerHitbox.Position.Y);
        } else if (direction.X > 0) {
            Sprite.FlipH = false;
            SwordCollision.Position = new Vector2(Mathf.Abs(SwordCollision.Position.X), SwordCollision.Position.Y);
            PlayerHitbox.Position = HauptHitbox;
        }
        // Geschwindigkeit reduzieren, wenn der Spieler angreift
        if (AnimationPlayer.CurrentAnimation == "light_attack") {
            currentSpeed *= 0.5f;
        } else if (AnimationPlayer.CurrentAnimation == "heavy_attack") {
            currentSpeed *= 0.15f;
        }
        // Blockieren stoppt die Bewegung
        if (IsBlocking()) {
            currentSpeed = 0;
        }
        if (IsDashing) {
            DashInProgress(DeltaTime);
        } else {
            // Normale Bewegung verarbeiten, wenn kein Dash aktiv ist
            if (direction != Vector2.Zero) {
                Velocity = new Vector2(direction.X * currentSpeed, Velocity.Y);
            } else {
                Velocity = new Vector2(Mathf.MoveToward(Velocity.X, 0, SPEED), Velocity.Y);
            }
            // Überprüfen, ob der Dash-Button gedrückt wurde mit eine Bewegungsrichtung und nicht schon am angreifen ist
            if (Input.IsActionJustPressed("dash") && direction != Vector2.Zero && CanDash && !IsAttacking()) {
                // Wenn der Player genug Stamina hat kann er dashen
                if (UseStamina(20)){
                    DashDirection = direction;
                    StartDash();
                }
            }
        }
    }
References AnimationPlayer, CanDash, DashDirection, DashInProgress(), HauptHitbox, IsAttacking(), IsBlocking(), IsDashing, PlayerHitbox, SPEED, Sprite, StartDash(), SwordCollision, and UseStamina().
Referenced by _PhysicsProcess().
IsAttacking()
bool Player.IsAttacking () inline
Überprüft, ob der Spieler gerade angreift.
Returns
true, wenn der Spieler angreift.
Definition at line 265 of file Player.cs.
{
        return AnimationPlayer.CurrentAnimation == "heavy_attack" || AnimationPlayer.CurrentAnimation == "light_attack";
    }
Referenced by HandleMovement(), and UpdateAnimations().
IsBlocking()
bool Player.IsBlocking () inline
Überprüft, ob der Spieler blockiert.
Returns
true, wenn der Spieler blockiert.
Definition at line 273 of file Player.cs.
{
        return AnimationPlayer.CurrentAnimation == "block";
    }
Referenced by HandleMovement(), TakeDamage(), and UpdateAnimations().
MaxHeal()
void Player.MaxHeal () inline
Heilt den Spieler vollständig, indem die aktuellen Lebenspunkte auf das Maximum gesetzt werden.
Definition at line 280 of file Player.cs.
{
        PlayerStats.Instance.SetCurrentHealth(PlayerStats.Instance.GetMaxHealthPoints());
    }
References PlayerStats.GetMaxHealthPoints(), PlayerStats.Instance, and PlayerStats.SetCurrentHealth().
Referenced by Checkpoint.OnPlayerBodyEntered().
OnSpawn()
void Player.OnSpawn (Vector2 position, string direction) inline private
Wird aufgerufen, wenn der Spieler an einer neuen Position spawnen soll.
Parameters
position Die Position, an der der Spieler spawnen soll.
direction Die Richtung, in die der Spieler schauen soll.
Definition at line 402 of file Player.cs.
{
        // Spielerposition auf die übergebene Position setzen
        if (direction == "right")
        {
            // Update the x value by adding 50 to it, keep the original y value
            Sprite.FlipH = false;
            position = position with { X = position.X + 25 };
        }
        else if (direction == "left")
        {
            // Update the x value by subtracting 50 from it, keep the original y value
            Sprite.FlipH = true;
            position = position with { X = position.X - 25 };
        }
        Position = position;
    }
Referenced by _Ready().
RegenerateStamina()
void Player.RegenerateStamina (float Amount, double delta) inline
Regeneriert die Stamina des Spielers, wenn er für eine bestimmte Zeit keine Stamina-verbrauchende Aktion durchgeführt hat.
Parameters
Amount Menge der Stamina, die regeneriert werden soll.
delta Zeit seit dem letzten Frame.
Definition at line 336 of file Player.cs.
{
        // Wenn die Verzögerungszeit erreicht wurde, regeneriere Stamina
        if (TimeSinceLastStaminaUse >= 1f) {
            PlayerStats.Instance.SetStamina(PlayerStats.Instance.GetStamina() + Amount * (float)delta); // Regeneriere Stamina abhängig von der Zeit
        }
    }
References PlayerStats.GetStamina(), PlayerStats.Instance, PlayerStats.SetStamina(), and TimeSinceLastStaminaUse.
Referenced by _PhysicsProcess().
Respawn()
void Player.Respawn () inline
Lässt den Spieler am Checkpoint spawnen.
Definition at line 372 of file Player.cs.
{
        var NavigationManager = GetNode<NavigationManager>("/root/NavigationManager");
        NavigationManager.GoToLevel(PlayerStats.Instance.GetRespawnLevelTag(), "spawn");
        BloodVials.ResetUses();
    }
References BloodVials, PlayerStats.GetRespawnLevelTag(), NavigationManager.GoToLevel(), PlayerStats.Instance, and BloodVial.ResetUses().
Referenced by TakeDamage().
SetSinAmount()
void Player.SetSinAmount (int Value) inline
Setzt den SinAmount des Spielers.
Parameters
Value Der neue Wert für den SinAmount.
Definition at line 391 of file Player.cs.
{
        // SinAmount muss immer >= 0 sein
        PlayerStats.Instance.SetSinAmount(Value);
        SinDisplay.Text = PlayerStats.Instance.GetSinAmount() + "";
    }
References PlayerStats.GetSinAmount(), PlayerStats.Instance, and PlayerStats.SetSinAmount().
Referenced by BaseEnemy.Die().
SlowPlayer()
void Player.SlowPlayer (float SlowAmount) inline
Verlangsamt den Spieler um einen bestimmten Prozentsatz.
Parameters
SlowAmount Der Prozentsatz, um den der Spieler verlangsamt werden soll.
Definition at line 365 of file Player.cs.
{
        Velocity = new Vector2(Velocity.X * SlowAmount, Velocity.Y);
    }
Referenced by Spike.OnPlayerBodyEntered(), and SpikeDynamic.OnPlayerBodyEntered().
StartDash()
void Player.StartDash () inline private
Startet den Dash-Prozess.
Definition at line 172 of file Player.cs.
{
        SetCollisionLayerValue(1,false);
        SetCollisionMaskValue(1,false);
        IsDashing = true;
        CanDash = false;
        DashTimer.Timeout += StopDash;
        DashTimer.Start();
        DashEffect.Start();
        DashTrailTimer = 0f;
    }
References CanDash, DashEffect, DashTimer, DashTrailTimer, IsDashing, and StopDash().
Referenced by HandleMovement().
StopDash()
void Player.StopDash () inline private
Stoppt den Dash.
Definition at line 252 of file Player.cs.
{
        IsDashing = false;
        DashEffect.Stop();
        DashTimer.Stop();
        DashTimer.Timeout -= StopDash;
        SetCollisionLayerValue(1,true);
        SetCollisionMaskValue(1,true);
    }
References DashEffect, DashTimer, IsDashing, and StopDash().
Referenced by StartDash(), and StopDash().
TakeDamage()
void Player.TakeDamage (Damage Damage) inline
Wendet Schaden auf den Spieler an. Reduziert die aktuellen Lebenspunkte basierend auf dem übergebenen Schaden und wendet einen Rückstoßeffekt an.
Parameters
Damage Instanz der Klasse Damage, die den physischen und wahren Schaden sowie den Rückstoß enthält.
Definition at line 289 of file Player.cs.
{
        float totalDamage = Damage.GetTrueDMG();
        if(!IsBlocking()){
            totalDamage += Damage.GetPhysicalDMG();
        } else {
            float CurrentStamina = PlayerStats.Instance.GetStamina();
            CurrentStamina -= Damage.GetPhysicalDMG();
            if(CurrentStamina < 0){
                totalDamage -= CurrentStamina;
            }
            PlayerStats.Instance.SetStamina(CurrentStamina);
        }
        PlayerStats.Instance.SetCurrentHealth(PlayerStats.Instance.GetCurrentHealth() - totalDamage);
        Position += Damage.GetPushAmount();
        // Überprüfe, ob der Spieler gestorben ist
        if (PlayerStats.Instance.GetCurrentHealth() <= 0){
            GD.Print("Spieler ist gestorben!");
            Respawn();
        }
    }
References PlayerStats.GetCurrentHealth(), Damage.GetPhysicalDMG(), Damage.GetPushAmount(), PlayerStats.GetStamina(), Damage.GetTrueDMG(), PlayerStats.Instance, IsBlocking(), Respawn(), PlayerStats.SetCurrentHealth(), and PlayerStats.SetStamina().
Referenced by BaseEnemy.CheckPlayerHit(), Spike.OnPlayerBodyEntered(), SpikeDynamic.OnPlayerBodyEntered(), Spike.OnTimerTimeout(), and SpikeDynamic.OnTimerTimeout().
UpdateAnimations()
void Player.UpdateAnimations () inline private
Aktualisiert die Animationen des Spielers.
Definition at line 425 of file Player.cs.
{
        if (Input.IsActionJustPressed("light_attack") && !IsDashing && !IsAttacking()) {
            if (UseStamina(10)){
                LastAttack = 1;
                AnimationPlayer.Play("light_attack");
            }
        } else if (Input.IsActionJustPressed("heavy_attack") && !IsDashing && !IsAttacking()) {
            if (UseStamina(25)){
                LastAttack = 2;
                AnimationPlayer.Play("heavy_attack");
            }
        }
        if (Input.IsActionPressed("block") && !IsDashing && !IsAttacking() && IsOnFloor()) {
            if (UseStamina(0)){
                AnimationPlayer.Play("block");
                LastAttack = 0;
            }
        }
        if (IsOnFloor() && !IsAttacking() && !IsBlocking()) {
            LastAttack = 0;
            if (Velocity.X == 0) {
                AnimationPlayer.Play("idle");
            } else {
                AnimationPlayer.Play("run");
            }
        } else if (!IsOnFloor() && !IsAttacking() && !IsBlocking()) {
            LastAttack = 0;
            if (Velocity.Y < 0) {
                AnimationPlayer.Play("jump");
            } else if (Velocity.Y > 0) {
                AnimationPlayer.Play("fall");
            }
        }
    }
References AnimationPlayer, IsAttacking(), IsBlocking(), IsDashing, LastAttack, and UseStamina().
Referenced by _PhysicsProcess().
UseStamina()
bool Player.UseStamina (float Amount) inline
Verbraucht eine bestimmte Menge an Stamina, falls genügend verfügbar ist. Setzt den Inaktivitäts-Timer zurück, wenn Stamina verbraucht wird.
Parameters
Amount Die Menge an Stamina, die verbraucht werden soll.
Returns
true, wenn genügend Stamina verfügbar war und die Aktion ausgeführt wurde; andernfalls false.
Definition at line 349 of file Player.cs.
{
        // Versucht, eine bestimmte Menge an Stamina zu verbrauchen.
        // Gibt true zurück, wenn genug Stamina verfügbar war; andernfalls false.
        if (PlayerStats.Instance.GetStamina() >= Amount) {
            PlayerStats.Instance.SetStamina(PlayerStats.Instance.GetStamina() - Amount);
            TimeSinceLastStaminaUse = 0f;
            return true;
        }
        return false;
    }
References PlayerStats.GetStamina(), PlayerStats.Instance, PlayerStats.SetStamina(), and TimeSinceLastStaminaUse.
Referenced by HandleJump(), HandleMovement(), and UpdateAnimations().
Member Data Documentation
AnimationPlayer
AnimationPlayer Player.AnimationPlayer private
Definition at line 24 of file Player.cs.
Referenced by _Ready(), HandleMovement(), and UpdateAnimations().
BloodVials
BloodVial Player.BloodVials private
Definition at line 30 of file Player.cs.
Referenced by _PhysicsProcess(), _Ready(), GetBloodVials(), and Respawn().
CanDash
bool Player.CanDash = true private
Definition at line 19 of file Player.cs.
Referenced by _PhysicsProcess(), HandleMovement(), and StartDash().
DashDirection
Vector2 Player.DashDirection = Vector2.Zero private
Definition at line 16 of file Player.cs.
Referenced by DashInProgress(), and HandleMovement().
DashEffect
Timer Player.DashEffect private
Definition at line 26 of file Player.cs.
Referenced by _Ready(), StartDash(), and StopDash().
DashSpeed
float Player.DashSpeed = 300f private
Definition at line 17 of file Player.cs.
Referenced by DashInProgress().
DashTimer
Timer Player.DashTimer private
Definition at line 27 of file Player.cs.
Referenced by _Ready(), CreateDashEffect(), StartDash(), and StopDash().
DashTrailInterval
float Player.DashTrailInterval = 0.05f private
Definition at line 20 of file Player.cs.
Referenced by DashInProgress().
DashTrailTimer
float Player.DashTrailTimer = 0f private
Definition at line 21 of file Player.cs.
Referenced by DashInProgress(), and StartDash().
HauptHitbox
Vector2 Player.HauptHitbox private
Definition at line 33 of file Player.cs.
Referenced by _Ready(), and HandleMovement().
IsDashing
bool Player.IsDashing = false private
Definition at line 18 of file Player.cs.
Referenced by HandleMovement(), StartDash(), StopDash(), and UpdateAnimations().
JUMP_VELOCITY
const float Player.JUMP_VELOCITY = -300f static private
Definition at line 12 of file Player.cs.
Referenced by HandleJump().
JumpCount
int Player.JumpCount = 0 private
Definition at line 14 of file Player.cs.
Referenced by HandleJump().
JumpMax
int Player.JumpMax = 2 private
Definition at line 13 of file Player.cs.
Referenced by HandleJump().
LastAttack
int Player.LastAttack = 0 private
Definition at line 34 of file Player.cs.
Referenced by GetDamage(), and UpdateAnimations().
PlayerHitbox
CollisionShape2D Player.PlayerHitbox private
Definition at line 29 of file Player.cs.
Referenced by _Ready(), and HandleMovement().
SinDisplay
Label Player.SinDisplay private
Definition at line 31 of file Player.cs.
Referenced by _Ready().
SPEED
const float Player.SPEED = 100f static private
Definition at line 11 of file Player.cs.
Referenced by HandleMovement().
Sprite
Sprite2D Player.Sprite private
Definition at line 25 of file Player.cs.
Referenced by _Ready(), CreateDashEffect(), GetDamage(), and HandleMovement().
SwordCollision
CollisionShape2D Player.SwordCollision private
Definition at line 28 of file Player.cs.
Referenced by _Ready(), and HandleMovement().
TimeSinceLastStaminaUse
float Player.TimeSinceLastStaminaUse = 0f private
Definition at line 37 of file Player.cs.
Referenced by _PhysicsProcess(), RegenerateStamina(), and UseStamina().
The documentation for this class was generated from the following file:
C:/Users/Youssef/Desktop/UNI/S4/ComputerspielEntwicklung/DasSpiel/anfaengerpraktikum/scripts/Player.cs