Anfaengerpraktikum: Hud Class Reference
Hud Class Reference
Klasse für das PauseMenu.
Public Member Functions
override void _Ready ()
Initialisierung der Referenzen. Findet die relevanten Knoten in der Szene und weist sie zu.
override void _Process (double DeltaTime)
Methode wird in jedem Frame ausgeführt.
void OnResumeButtonPressed ()
Signal für den Resume-Button.
void OnSaveButtonPressed ()
Signal für den Save-Button.
void OnSaveMenuButtonPressed ()
Signal für den SaveAndReturnToMenu-Button.
void OnSaveQuitButtonPressed ()
Signal für den SaveAndQuit-Button.
Private Member Functions
void TogglePause ()
Toggled die Pause Funktion.
Private Attributes
AnimationPlayer AnimationPlayer
CenterContainer Buttons
bool Enabled
Detailed Description
Klasse für das PauseMenu.
Definition at line 8 of file Hud.cs.
Member Function Documentation
_Process()
override void Hud._Process (double DeltaTime) inline
Methode wird in jedem Frame ausgeführt.
Parameters
DeltaTime Zeit seit dem letzten Frame.
Definition at line 29 of file Hud.cs.
{
        if(Input.IsActionJustPressed("escape")){
            TogglePause();
        }
    }
References TogglePause().
_Ready()
override void Hud._Ready () inline
Initialisierung der Referenzen. Findet die relevanten Knoten in der Szene und weist sie zu.
Definition at line 19 of file Hud.cs.
{
        AnimationPlayer = GetNode<AnimationPlayer>("PauseMenu/AnimationPlayer");
        Buttons = GetNode<CenterContainer>("PauseMenu/Buttons");
        AnimationPlayer.Play("RESET");
    }
References AnimationPlayer, and Buttons.
OnResumeButtonPressed()
void Hud.OnResumeButtonPressed () inline
Signal für den Resume-Button.
Definition at line 53 of file Hud.cs.
{
        TogglePause();
    }
References TogglePause().
OnSaveButtonPressed()
void Hud.OnSaveButtonPressed () inline
Signal für den Save-Button.
Definition at line 60 of file Hud.cs.
{
        StorageManager.Instance.SaveAll(StorageManager.Instance.GetLastSaveId());
    }
References StorageManager.GetLastSaveId(), StorageManager.Instance, and StorageManager.SaveAll().
OnSaveMenuButtonPressed()
void Hud.OnSaveMenuButtonPressed () inline
Signal für den SaveAndReturnToMenu-Button.
Definition at line 67 of file Hud.cs.
{
        StorageManager.Instance.SaveAll(StorageManager.Instance.GetLastSaveId());
        NavigationManager.Instance.GoToLevel("main_menu", null);
        PlayerStats.Instance.Reload();
        GetTree().Paused = false;
    }
References StorageManager.GetLastSaveId(), NavigationManager.GoToLevel(), NavigationManager.Instance, PlayerStats.Instance, StorageManager.Instance, PlayerStats.Reload(), and StorageManager.SaveAll().
OnSaveQuitButtonPressed()
void Hud.OnSaveQuitButtonPressed () inline
Signal für den SaveAndQuit-Button.
Definition at line 77 of file Hud.cs.
{
        StorageManager.Instance.SaveAll(StorageManager.Instance.GetLastSaveId());
        GetTree().Quit();
    }
References StorageManager.GetLastSaveId(), StorageManager.Instance, and StorageManager.SaveAll().
TogglePause()
void Hud.TogglePause () inline private
Toggled die Pause Funktion.
Definition at line 38 of file Hud.cs.
{
        Enabled = !Enabled;
        GetTree().Paused = Enabled;
        if(Enabled){
            AnimationPlayer.Play("Pause");
            Buttons.Visible = true;
        } else {
            AnimationPlayer.PlayBackwards("Pause");
            Buttons.Visible = false;
        }
    }
References AnimationPlayer, and Enabled.
Referenced by _Process(), and OnResumeButtonPressed().
Member Data Documentation
AnimationPlayer
AnimationPlayer Hud.AnimationPlayer private
Definition at line 10 of file Hud.cs.
Referenced by _Ready(), and TogglePause().
Buttons
CenterContainer Hud.Buttons private
Definition at line 11 of file Hud.cs.
Referenced by _Ready().
Enabled
bool Hud.Enabled private
Definition at line 12 of file Hud.cs.
Referenced by TogglePause().
The documentation for this class was generated from the following file:
C:/Users/Youssef/Desktop/UNI/S4/ComputerspielEntwicklung/DasSpiel/anfaengerpraktikum/scripts/Hud.cs