Anfaengerpraktikum: BloodVial Class Reference
BloodVial Class Reference
Klasse für die Interaktion zum heilen.
Public Member Functions
override void _Ready ()
Initialisierung der Referenzen. Findet die relevanten Knoten in der Szene und weist sie zu.
void UseBloodVial ()
Versucht ein Bloodvial zu verwenden um den Spieler zu Heilen.
void ResetUses ()
Setzt die Anzahl der Bloodvials auf das Maximum.
void AddMaxUses (int Amount)
Verbessert die Maximale Anzahl an Bloodvials um die angegebene Anzahl.
void LevelHealAmount ()
Verbessert den HealAMount eines Bloodvials um 25.
Detailed Description
Klasse für die Interaktion zum heilen.
Definition at line 8 of file BloodVial.cs.
Member Function Documentation
_Ready()
override void BloodVial._Ready () inline
Initialisierung der Referenzen. Findet die relevanten Knoten in der Szene und weist sie zu.
Definition at line 14 of file BloodVial.cs.
{
        Text = PlayerStats.Instance.GetBVCurrentUses() + "";
    }
References PlayerStats.GetBVCurrentUses(), and PlayerStats.Instance.
AddMaxUses()
void BloodVial.AddMaxUses (int Amount) inline
Verbessert die Maximale Anzahl an Bloodvials um die angegebene Anzahl.
Parameters
int Amount, um die MaxUses erhöht wird.
Definition at line 40 of file BloodVial.cs.
{
        PlayerStats.Instance.SetBVMaxUses(PlayerStats.Instance.GetBVMaxUses() + Amount);
        ResetUses();
    }
References PlayerStats.GetBVMaxUses(), PlayerStats.Instance, ResetUses(), and PlayerStats.SetBVMaxUses().
LevelHealAmount()
void BloodVial.LevelHealAmount () inline
Verbessert den HealAMount eines Bloodvials um 25.
Definition at line 48 of file BloodVial.cs.
{
        PlayerStats.Instance.SetBVHealAmount(PlayerStats.Instance.GetBVHealAmount() + 25);
    }
References PlayerStats.GetBVHealAmount(), PlayerStats.Instance, and PlayerStats.SetBVHealAmount().
ResetUses()
void BloodVial.ResetUses () inline
Setzt die Anzahl der Bloodvials auf das Maximum.
Definition at line 31 of file BloodVial.cs.
{
        PlayerStats.Instance.SetBVCurrentUses(PlayerStats.Instance.GetBVMaxUses());
        Text = PlayerStats.Instance.GetBVCurrentUses() + "";
    }
References PlayerStats.GetBVCurrentUses(), PlayerStats.GetBVMaxUses(), PlayerStats.Instance, and PlayerStats.SetBVCurrentUses().
Referenced by AddMaxUses(), Checkpoint.OnPlayerBodyEntered(), and Player.Respawn().
UseBloodVial()
void BloodVial.UseBloodVial () inline
Versucht ein Bloodvial zu verwenden um den Spieler zu Heilen.
Definition at line 21 of file BloodVial.cs.
{
        if(PlayerStats.Instance.GetBVCurrentUses() <= 0) return;
        PlayerStats.Instance.SetBVCurrentUses(PlayerStats.Instance.GetBVCurrentUses() - 1);
        Text = PlayerStats.Instance.GetBVCurrentUses() + "";
        PlayerStats.Instance.SetCurrentHealth(PlayerStats.Instance.GetCurrentHealth() + PlayerStats.Instance.GetBVHealAmount());
    }
References PlayerStats.GetBVCurrentUses(), PlayerStats.GetBVHealAmount(), PlayerStats.GetCurrentHealth(), PlayerStats.Instance, PlayerStats.SetBVCurrentUses(), and PlayerStats.SetCurrentHealth().
Referenced by Player._PhysicsProcess().
The documentation for this class was generated from the following file:
C:/Users/Youssef/Desktop/UNI/S4/ComputerspielEntwicklung/DasSpiel/anfaengerpraktikum/scripts/BloodVial.cs