Anfaengerpraktikum: HealthBar Class Reference
HealthBar Class Reference
Klasse für die Gesundheitsleiste des Spielers. Synchronisiert die Anzeige der HealthBar mit den Lebenspunkten des Spielers.
Public Member Functions
override void _Ready ()
Initialisiert die HealthBar und verbindet sie mit den Lebenspunkten des Spielers. Lädt den Spieler-Knoten und setzt die maximale und aktuelle Gesundheit in der HealthBar.
override void _Process (double DeltaTime)
Aktualisiert die HealthBar in jedem Frame. Synchronisiert die Anzeige der aktuellen Lebenspunkte mit den Werten des Spielers.
Detailed Description
Klasse für die Gesundheitsleiste des Spielers. Synchronisiert die Anzeige der HealthBar mit den Lebenspunkten des Spielers.
Definition at line 7 of file HealthBar.cs.
Member Function Documentation
_Process()
override void HealthBar._Process (double DeltaTime) inline
Aktualisiert die HealthBar in jedem Frame. Synchronisiert die Anzeige der aktuellen Lebenspunkte mit den Werten des Spielers.
Parameters
delta Zeit seit dem letzten Frame (wird nicht direkt genutzt).
Definition at line 24 of file HealthBar.cs.
{
        // Aktualisiere den Wert der HealthBar basierend auf der aktuellen Gesundheit des Spielers
        Value = PlayerStats.Instance.GetCurrentHealth();
    }
References PlayerStats.GetCurrentHealth(), and PlayerStats.Instance.
_Ready()
override void HealthBar._Ready () inline
Initialisiert die HealthBar und verbindet sie mit den Lebenspunkten des Spielers. Lädt den Spieler-Knoten und setzt die maximale und aktuelle Gesundheit in der HealthBar.
Definition at line 13 of file HealthBar.cs.
{
        // Setze die maximale Gesundheit der HealthBar basierend auf der Spieler-MaxHealth
        MaxValue = PlayerStats.Instance.GetMaxHealthPoints();
        Value = PlayerStats.Instance.GetCurrentHealth();
    }
References PlayerStats.GetCurrentHealth(), PlayerStats.GetMaxHealthPoints(), and PlayerStats.Instance.
The documentation for this class was generated from the following file:
C:/Users/Youssef/Desktop/UNI/S4/ComputerspielEntwicklung/DasSpiel/anfaengerpraktikum/scripts/HealthBar.cs