Anfaengerpraktikum: NavigationManager Class Reference
NavigationManager Class Reference
Der NavigationManager ist für das Laden von Leveln und das Spawnen des Spielers verantwortlich. Der NavigationManager ist ein Singleton, der in der Haupt-Szene platziert wird und von anderen Skripten verwendet wird, um Level zu laden und den Spieler zu spawnen.
Public Member Functions
delegate void OnTriggerPlayerSpawnEventHandler (Vector2 Position, string Direction)
Das Signal, das ausgelöst wird, wenn der Spieler spawnen soll.
override void _Ready ()
Initialisiert den NavigationManager und setzt ihn als Singleton.
void GoToLevel (string LevelTag, string DestinationTag)
Lädt das angegebene Level und setzt das Ziel-Tag für den Spieler-Spawn.
void TriggerPlayerSpawn (Vector2 Position, string Direction)
Lädt das angegebene Level und setzt das Ziel-Tag für den Spieler-Spawn.
Properties
static NavigationManager Instance [get, private set]
string SpawnDoorTag [get, private set]
Private Member Functions
void DeferredChangeScene (PackedScene SceneToLoad)
Diese Methode wird aufgerufen, um die Szene zu wechseln.
Static Private Attributes
static readonly PackedScene SceneMainMenu = (PackedScene)GD.Load("res://Scenes/main_menu.tscn")
static readonly PackedScene SceneIntro = (PackedScene)GD.Load("res://Scenes/intro.tscn")
static readonly PackedScene SceneLevel1 = (PackedScene)GD.Load("res://Scenes/level1.tscn")
static readonly PackedScene SceneBoss = (PackedScene)GD.Load("res://Scenes/bossRoom.tscn")
static readonly PackedScene SceneLevelOne = (PackedScene)GD.Load("res://Scenes/level_one.tscn")
static readonly PackedScene SceneLevelTwo = (PackedScene)GD.Load("res://Scenes/level_two.tscn")
Detailed Description
Der NavigationManager ist für das Laden von Leveln und das Spawnen des Spielers verantwortlich. Der NavigationManager ist ein Singleton, der in der Haupt-Szene platziert wird und von anderen Skripten verwendet wird, um Level zu laden und den Spieler zu spawnen.
Definition at line 7 of file NavigationManager.cs.
Member Function Documentation
_Ready()
override void NavigationManager._Ready () inline
Initialisiert den NavigationManager und setzt ihn als Singleton.
Definition at line 32 of file NavigationManager.cs.
{
        Instance = this;
    }
References Instance.
DeferredChangeScene()
void NavigationManager.DeferredChangeScene (PackedScene SceneToLoad) inline private
Diese Methode wird aufgerufen, um die Szene zu wechseln.
Parameters
SceneToLoad Die Szene, die geladen werden soll.
Definition at line 83 of file NavigationManager.cs.
    {
        GetTree().ChangeSceneToPacked(SceneToLoad);
    }
Referenced by GoToLevel().
GoToLevel()
void NavigationManager.GoToLevel (string LevelTag, string DestinationTag) inline
Lädt das angegebene Level und setzt das Ziel-Tag für den Spieler-Spawn.
Parameters
LevelTag Das Tag des Levels, das geladen werden soll.
DestinationTag Das Tag der Tür, an der der Spieler spawnen soll.
Definition at line 41 of file NavigationManager.cs.
    {
        PackedScene SceneToLoad = null;
        // Bestimmen, welches Level geladen werden soll
        switch (LevelTag)
        {
            case "main_menu":
                SceneToLoad = SceneMainMenu;
                break;
            case "intro":
                SceneToLoad = SceneIntro;
                break;
            case "level1":
                SceneToLoad = SceneLevel1;
                break;
            case "bossRoom":
                SceneToLoad = SceneBoss;
                break;
            case "level_one":
                SceneToLoad = SceneLevelOne;
                break;
            case "level_two":
                SceneToLoad = SceneLevelTwo;
                break;
        }
        // Überprüfen, ob eine Szene ausgewählt wurde und diese dann laden
        if (SceneToLoad != null){
            if(SceneToLoad != SceneMainMenu){
                PlayerStats.Instance.SetCurrentLevelTag(LevelTag);
                SpawnDoorTag = DestinationTag;
            }
            // Verwendung der ChangeSceneToPacked-Methode in Godot 4
            CallDeferred(nameof(DeferredChangeScene), SceneToLoad);
        }
    }
References DeferredChangeScene(), PlayerStats.Instance, SceneBoss, SceneIntro, SceneLevel1, SceneLevelOne, SceneLevelTwo, SceneMainMenu, PlayerStats.SetCurrentLevelTag(), and SpawnDoorTag.
Referenced by MainMenu.OnContinueButtonPressed(), Door.OnPlayerBodyEntered(), MainMenu.OnSave1SelectPressed(), MainMenu.OnSave2SelectPressed(), MainMenu.OnSave3SelectPressed(), Hud.OnSaveMenuButtonPressed(), and Player.Respawn().
OnTriggerPlayerSpawnEventHandler()
delegate void NavigationManager.OnTriggerPlayerSpawnEventHandler (Vector2 Position, string Direction)
Das Signal, das ausgelöst wird, wenn der Spieler spawnen soll.
Parameters
Position Die Position, an der der Spieler spawnen soll.
Direction Die Richtung, in die der Spieler schauen soll.
TriggerPlayerSpawn()
void NavigationManager.TriggerPlayerSpawn (Vector2 Position, string Direction) inline
Lädt das angegebene Level und setzt das Ziel-Tag für den Spieler-Spawn.
Parameters
Position Die Position, an der der Spieler spawnen soll.
Direction Die Richtung, in die der Spieler schauen soll.
Definition at line 93 of file NavigationManager.cs.
    {
        EmitSignal(SignalName.OnTriggerPlayerSpawn, Position, Direction);
    }
Member Data Documentation
SceneBoss
readonly PackedScene NavigationManager.SceneBoss = (PackedScene)GD.Load("res://Scenes/bossRoom.tscn") static private
Definition at line 14 of file NavigationManager.cs.
Referenced by GoToLevel().
SceneIntro
readonly PackedScene NavigationManager.SceneIntro = (PackedScene)GD.Load("res://Scenes/intro.tscn") static private
Definition at line 12 of file NavigationManager.cs.
Referenced by GoToLevel().
SceneLevel1
readonly PackedScene NavigationManager.SceneLevel1 = (PackedScene)GD.Load("res://Scenes/level1.tscn") static private
Definition at line 13 of file NavigationManager.cs.
Referenced by GoToLevel().
SceneLevelOne
readonly PackedScene NavigationManager.SceneLevelOne = (PackedScene)GD.Load("res://Scenes/level_one.tscn") static private
Definition at line 15 of file NavigationManager.cs.
Referenced by GoToLevel().
SceneLevelTwo
readonly PackedScene NavigationManager.SceneLevelTwo = (PackedScene)GD.Load("res://Scenes/level_two.tscn") static private
Definition at line 16 of file NavigationManager.cs.
Referenced by GoToLevel().
SceneMainMenu
readonly PackedScene NavigationManager.SceneMainMenu = (PackedScene)GD.Load("res://Scenes/main_menu.tscn") static private
Definition at line 11 of file NavigationManager.cs.
Referenced by GoToLevel().
Property Documentation
Instance
NavigationManager NavigationManager.Instance static get private set
Definition at line 9 of file NavigationManager.cs.
{ get; private set; }
Referenced by _Ready(), MainMenu.OnContinueButtonPressed(), MainMenu.OnSave1SelectPressed(), MainMenu.OnSave2SelectPressed(), MainMenu.OnSave3SelectPressed(), and Hud.OnSaveMenuButtonPressed().
SpawnDoorTag
string NavigationManager.SpawnDoorTag get private set
Definition at line 19 of file NavigationManager.cs.
{ get; private set; }
Referenced by LevelManager._Ready(), and GoToLevel().
The documentation for this class was generated from the following file:
C:/Users/Youssef/Desktop/UNI/S4/ComputerspielEntwicklung/DasSpiel/anfaengerpraktikum/scripts/NavigationManager.cs