Anfaengerpraktikum: StorageManager Class Reference
StorageManager Class Reference
Klasse für das Speichern und Laden von Daten.
Public Member Functions
override void _Ready ()
Initialisierung der Instanz und erstes laden der Einstellungen.
void LoadSettings ()
Laden der Einstellungen.
void LoadGameFile (int id)
Laden eines Spielstandes.
void SaveAll (int id)
Speichern der Einstellungen und eines Spielstandes.
void SaveSettings ()
Speichern der Einstellungen.
void SaveGameFile (int id)
Speichern eines Spielstandes.
void SetLastSaveId (int id)
Setter für LastSaveId.
int GetLastSaveId ()
Getter für LastSaveId.
void SetSaves (int Saves)
Setter für Saves.
int GetSaves ()
Getter für Saves.
Properties
static StorageManager Instance [get, private set]
Private Attributes
String[] PathSave = {"user://save1.dat", "user://save2.dat", "user://save3.dat"}
int LastSaveId = -1
int Saves = 0
Static Private Attributes
const String PathSettings = "user://settings.txt"
Detailed Description
Klasse für das Speichern und Laden von Daten.
Definition at line 8 of file StorageManager.cs.
Member Function Documentation
_Ready()
override void StorageManager._Ready () inline
Initialisierung der Instanz und erstes laden der Einstellungen.
Definition at line 20 of file StorageManager.cs.
{
        LoadSettings();
        Instance = this;
    }
References Instance, and LoadSettings().
GetLastSaveId()
int StorageManager.GetLastSaveId () inline
Getter für LastSaveId.
Returns
int LastSaveId
Definition at line 118 of file StorageManager.cs.
{
        return LastSaveId;
    }
References LastSaveId.
Referenced by MainMenu._Ready(), MainMenu.OnContinueButtonPressed(), Hud.OnSaveButtonPressed(), Hud.OnSaveMenuButtonPressed(), and Hud.OnSaveQuitButtonPressed().
GetSaves()
int StorageManager.GetSaves () inline
Getter für Saves.
Returns
int Saves
Definition at line 134 of file StorageManager.cs.
{
        return Saves;
    }
References Saves.
Referenced by MainMenu.Change(), MainMenu.OnDeleteConfirmationConfirmed(), MainMenu.OnSave1SelectPressed(), MainMenu.OnSave2SelectPressed(), and MainMenu.OnSave3SelectPressed().
LoadGameFile()
void StorageManager.LoadGameFile (int id) inline
Laden eines Spielstandes.
Parameters
Id des Spielstandes.
Definition at line 43 of file StorageManager.cs.
{
        if(!FileAccess.FileExists(PathSave[id])){
            return;
        }
        FileAccess File = FileAccess.Open(PathSave[id], FileAccess.ModeFlags.Read);
        PlayerStats.Instance.SetRespawnLevelTag((String) File.GetVar());
        PlayerStats.Instance.SetCurrentLevelTag((String) File.GetVar());
        PlayerStats.Instance.SetSpawnPoint((Vector2) File.GetVar());
        PlayerStats.Instance.SetPosition((Vector2) File.GetVar());
        PlayerStats.Instance.SetSinAmount((int) File.GetVar());
        PlayerStats.Instance.SetMaxHealthPoints((float) File.GetVar());
        PlayerStats.Instance.SetCurrentHealth((float) File.GetVar());
        PlayerStats.Instance.SetMaxStamina((float) File.GetVar());
        PlayerStats.Instance.SetStamina((float) File.GetVar());
        PlayerStats.Instance.SetBVHealAmount((int) File.GetVar());
        PlayerStats.Instance.SetBVMaxUses((int) File.GetVar());
        PlayerStats.Instance.SetBVCurrentUses((int) File.GetVar());
        File.Close();
    }
References PlayerStats.Instance, PathSave, PlayerStats.SetBVCurrentUses(), PlayerStats.SetBVHealAmount(), PlayerStats.SetBVMaxUses(), PlayerStats.SetCurrentHealth(), PlayerStats.SetCurrentLevelTag(), PlayerStats.SetMaxHealthPoints(), PlayerStats.SetMaxStamina(), PlayerStats.SetPosition(), PlayerStats.SetRespawnLevelTag(), PlayerStats.SetSinAmount(), PlayerStats.SetSpawnPoint(), and PlayerStats.SetStamina().
Referenced by MainMenu.OnContinueButtonPressed(), MainMenu.OnSave1SelectPressed(), MainMenu.OnSave2SelectPressed(), and MainMenu.OnSave3SelectPressed().
LoadSettings()
void StorageManager.LoadSettings () inline
Laden der Einstellungen.
Definition at line 28 of file StorageManager.cs.
{
        if(!FileAccess.FileExists(PathSettings)){
            return;
        }
        FileAccess File = FileAccess.Open(PathSettings, FileAccess.ModeFlags.Read);
        Saves = (int) File.GetVar();
        LastSaveId = (int) File.GetVar();
        File.Close();
    }
References LastSaveId, PathSettings, and Saves.
Referenced by _Ready().
SaveAll()
void StorageManager.SaveAll (int id) inline
Speichern der Einstellungen und eines Spielstandes.
Parameters
Id des Spielstandes.
Definition at line 68 of file StorageManager.cs.
{
        SaveGameFile(id);
        SaveSettings();
    }
References SaveGameFile(), and SaveSettings().
Referenced by Hud.OnSaveButtonPressed(), Hud.OnSaveMenuButtonPressed(), and Hud.OnSaveQuitButtonPressed().
SaveGameFile()
void StorageManager.SaveGameFile (int id) inline
Speichern eines Spielstandes.
Parameters
Id des Spielstandes.
Definition at line 88 of file StorageManager.cs.
{
        FileAccess File = FileAccess.Open(PathSave[id], FileAccess.ModeFlags.Write);
        File.StoreVar(PlayerStats.Instance.GetRespawnLevelTag());
        File.StoreVar(PlayerStats.Instance.GetCurrentLevelTag());
        File.StoreVar(PlayerStats.Instance.GetSpawnPoint());
        File.StoreVar(PlayerStats.Instance.GetPosition());
        File.StoreVar(PlayerStats.Instance.GetSinAmount());
        File.StoreVar(PlayerStats.Instance.GetMaxHealthPoints());
        File.StoreVar(PlayerStats.Instance.GetCurrentHealth());
        File.StoreVar(PlayerStats.Instance.GetMaxStamina());
        File.StoreVar(PlayerStats.Instance.GetStamina());
        File.StoreVar(PlayerStats.Instance.GetBVHealAmount());
        File.StoreVar(PlayerStats.Instance.GetBVMaxUses());
        File.StoreVar(PlayerStats.Instance.GetBVCurrentUses());
        File.Close();
    }
References PlayerStats.GetBVCurrentUses(), PlayerStats.GetBVHealAmount(), PlayerStats.GetBVMaxUses(), PlayerStats.GetCurrentHealth(), PlayerStats.GetCurrentLevelTag(), PlayerStats.GetMaxHealthPoints(), PlayerStats.GetMaxStamina(), PlayerStats.GetPosition(), PlayerStats.GetRespawnLevelTag(), PlayerStats.GetSinAmount(), PlayerStats.GetSpawnPoint(), PlayerStats.GetStamina(), PlayerStats.Instance, and PathSave.
Referenced by SaveAll().
SaveSettings()
void StorageManager.SaveSettings () inline
Speichern der Einstellungen.
Definition at line 76 of file StorageManager.cs.
{
        FileAccess File = FileAccess.Open(PathSettings, FileAccess.ModeFlags.Write);
        File.StoreVar(Saves);
        File.StoreVar(LastSaveId);
        File.Close();
    }
References LastSaveId, PathSettings, and Saves.
Referenced by MainMenu.OnQuitButtonPressed(), and SaveAll().
SetLastSaveId()
void StorageManager.SetLastSaveId (int id) inline
Setter für LastSaveId.
Parameters
int LastSaveId
Definition at line 110 of file StorageManager.cs.
{
        LastSaveId = id;
    }
References LastSaveId.
Referenced by MainMenu.OnSave1SelectPressed(), MainMenu.OnSave2SelectPressed(), and MainMenu.OnSave3SelectPressed().
SetSaves()
void StorageManager.SetSaves (int Saves) inline
Setter für Saves.
Parameters
int Saves
Definition at line 126 of file StorageManager.cs.
{
        this.Saves = Saves;
    }
References Saves.
Referenced by MainMenu.OnDeleteConfirmationConfirmed(), MainMenu.OnSave1SelectPressed(), MainMenu.OnSave2SelectPressed(), and MainMenu.OnSave3SelectPressed().
Member Data Documentation
LastSaveId
int StorageManager.LastSaveId = -1 private
Definition at line 13 of file StorageManager.cs.
Referenced by GetLastSaveId(), LoadSettings(), SaveSettings(), and SetLastSaveId().
PathSave
String [] StorageManager.PathSave = {"user://save1.dat", "user://save2.dat", "user://save3.dat"} private
Definition at line 12 of file StorageManager.cs.
{"user://save1.dat", "user://save2.dat", "user://save3.dat"};
Referenced by LoadGameFile(), and SaveGameFile().
PathSettings
const String StorageManager.PathSettings = "user://settings.txt" static private
Definition at line 11 of file StorageManager.cs.
Referenced by LoadSettings(), and SaveSettings().
Saves
int StorageManager.Saves = 0 private
Definition at line 14 of file StorageManager.cs.
Referenced by GetSaves(), LoadSettings(), SaveSettings(), and SetSaves().
Property Documentation
Instance
StorageManager StorageManager.Instance static get private set
Definition at line 10 of file StorageManager.cs.
{ get; private set; }
Referenced by MainMenu._Ready(), _Ready(), MainMenu.Change(), MainMenu.OnContinueButtonPressed(), MainMenu.OnDeleteConfirmationConfirmed(), MainMenu.OnQuitButtonPressed(), MainMenu.OnSave1SelectPressed(), MainMenu.OnSave2SelectPressed(), MainMenu.OnSave3SelectPressed(), Hud.OnSaveButtonPressed(), Hud.OnSaveMenuButtonPressed(), and Hud.OnSaveQuitButtonPressed().
The documentation for this class was generated from the following file:
C:/Users/Youssef/Desktop/UNI/S4/ComputerspielEntwicklung/DasSpiel/anfaengerpraktikum/scripts/StorageManager.cs