Anfaengerpraktikum: Damage Class Reference
Damage Class Reference
Repräsentiert den Schaden, der von Charakteren oder Gegnern verursacht wird. Beinhaltet physischen Schaden, wahren Schaden und den Rückstoßeffekt.
Public Member Functions
Damage (float PhysicalDMG, float TrueDMG, Vector2 PushAmount, Node2D Source)
Konstruktor für die Damage-Klasse.
float GetPhysicalDMG ()
Gibt den physischen Schaden zurück.
float GetTrueDMG ()
Gibt den wahren Schaden zurück.
Vector2 GetPushAmount ()
Gibt den Rückstoßvektor zurück.
Node2D GetSource ()
Gibt die Ursache zurück.
Private Attributes
float PhysicalDMG
float TrueDMG
Vector2 PushAmount
Node2D Source
Detailed Description
Repräsentiert den Schaden, der von Charakteren oder Gegnern verursacht wird. Beinhaltet physischen Schaden, wahren Schaden und den Rückstoßeffekt.
Definition at line 7 of file Damage.cs.
Constructor & Destructor Documentation
Damage()
Damage.Damage (float PhysicalDMG, float TrueDMG, Vector2 PushAmount, Node2D Source) inline
Konstruktor für die Damage-Klasse.
Parameters
PhysicalDMG Der physische Schaden.
TrueDMG Der wahre Schaden.
PushAmount Der Rückstoßvektor.
Definition at line 20 of file Damage.cs.
{
        this.PhysicalDMG = PhysicalDMG;
        this.TrueDMG = TrueDMG;
        this.PushAmount = PushAmount;
        this.Source = Source;
    }
References PhysicalDMG, PushAmount, Source, and TrueDMG.
Member Function Documentation
GetPhysicalDMG()
float Damage.GetPhysicalDMG () inline
Gibt den physischen Schaden zurück.
Returns
Der physische Schaden.
Definition at line 31 of file Damage.cs.
{
        return PhysicalDMG;
    }
References PhysicalDMG.
Referenced by BaseEnemy.TakeDamage(), and Player.TakeDamage().
GetPushAmount()
Vector2 Damage.GetPushAmount () inline
Gibt den Rückstoßvektor zurück.
Returns
Der Rückstoßvektor.
Definition at line 47 of file Damage.cs.
{
        return PushAmount;
    }
References PushAmount.
Referenced by BaseEnemy.TakeDamage(), and Player.TakeDamage().
GetSource()
Node2D Damage.GetSource () inline
Gibt die Ursache zurück.
Returns
Die Ursache.
Definition at line 55 of file Damage.cs.
{
        return Source;
    }
References Source.
Referenced by BaseEnemy.TakeDamage().
GetTrueDMG()
float Damage.GetTrueDMG () inline
Gibt den wahren Schaden zurück.
Returns
Der wahre Schaden.
Definition at line 39 of file Damage.cs.
{
        return TrueDMG;
    }
References TrueDMG.
Referenced by BaseEnemy.TakeDamage(), and Player.TakeDamage().
Member Data Documentation
PhysicalDMG
float Damage.PhysicalDMG private
Definition at line 9 of file Damage.cs.
Referenced by Damage(), and GetPhysicalDMG().
PushAmount
Vector2 Damage.PushAmount private
Definition at line 11 of file Damage.cs.
Referenced by Damage(), and GetPushAmount().
Source
Node2D Damage.Source private
Definition at line 12 of file Damage.cs.
Referenced by Damage(), and GetSource().
TrueDMG
float Damage.TrueDMG private
Definition at line 10 of file Damage.cs.
Referenced by Damage(), and GetTrueDMG().
The documentation for this class was generated from the following file:
C:/Users/Youssef/Desktop/UNI/S4/ComputerspielEntwicklung/DasSpiel/anfaengerpraktikum/scripts/Damage.cs