Anfaengerpraktikum: StaminaBar Class Reference
StaminaBar Class Reference
Klasse für die Ausdauerleiste des Spielers. Synchronisiert die Anzeige der StaminaBar mit der Ausdauer des Spielers.
Public Member Functions
override void _Ready ()
Initialisiert die StaminaBar und verbindet sie mit der Ausdauer des Spielers. Lädt den Spieler-Knoten und setzt die maximale und aktuelle Ausdauer in der StaminaBar.
override void _Process (double DeltaTime)
Aktualisiert die StaminaBar in jedem Frame. Synchronisiert die Anzeige der aktuellen Ausdauer mit den Werten des Spielers.
Detailed Description
Klasse für die Ausdauerleiste des Spielers. Synchronisiert die Anzeige der StaminaBar mit der Ausdauer des Spielers.
Definition at line 7 of file StaminaBar.cs.
Member Function Documentation
_Process()
override void StaminaBar._Process (double DeltaTime) inline
Aktualisiert die StaminaBar in jedem Frame. Synchronisiert die Anzeige der aktuellen Ausdauer mit den Werten des Spielers.
Parameters
delta Zeit seit dem letzten Frame (wird nicht direkt genutzt).
Definition at line 24 of file StaminaBar.cs.
{
        // Aktualisiere den Wert der StaminaBar basierend auf der aktuellen Ausdauer des Spielers
        Value = PlayerStats.Instance.GetStamina();
    }
References PlayerStats.GetStamina(), and PlayerStats.Instance.
_Ready()
override void StaminaBar._Ready () inline
Initialisiert die StaminaBar und verbindet sie mit der Ausdauer des Spielers. Lädt den Spieler-Knoten und setzt die maximale und aktuelle Ausdauer in der StaminaBar.
Definition at line 13 of file StaminaBar.cs.
{
        // Setze die maximale Ausdauer der StaminaBar basierend auf der Spieler-MaxStamina
        MaxValue = PlayerStats.Instance.GetMaxStamina();
        Value = PlayerStats.Instance.GetStamina();
    }
References PlayerStats.GetMaxStamina(), PlayerStats.GetStamina(), and PlayerStats.Instance.
The documentation for this class was generated from the following file:
C:/Users/Youssef/Desktop/UNI/S4/ComputerspielEntwicklung/DasSpiel/anfaengerpraktikum/scripts/StaminaBar.cs